sudo: true
language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
before_script: 
  - npm install -g @angular/cli
  - cd ParkPalWeb
  - npm install
script: 
  - ng build --prod
branches:
  only:
    - master
