matrix:
    include:
        - language: csharp
          solution: ParkPal.sln
          
        - language: node_js
            before_script:
                - npm install -g firebase-tools
                - npm install -g @angular/cli
            script:
                - ng build --prod
