matrix:
    include:
        notifications:
            email: false
        - language: csharp
          solution: ParkPal.sln
          
        - language: node_js
          before_script:
            - npm install -g @angular/cli
          script:
            - ng build --prod
