matrix:
    include:
        
        # safelist
        branches:
            only:
                - master
          
        - language: node_js
          before_script:
            - npm install -g @angular/cli
          script:
            - ng build --prod
            
